<a href="https://colab.research.google.com/github/turgonboyev/Google_Colab_uchun/blob/main/diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.shape

(768, 9)

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
df.info

<bound method DataFrame.info of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   5

In [8]:
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

x_train = train_set.drop(['Outcome'], axis=1).copy()
y_train = train_set['Outcome']

print(x_train)
print(y_train)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
60             2       84              0              0        0   0.0   
618            9      112             82             24        0  28.2   
346            1      139             46             19       83  28.7   
294            0      161             50              0        0  21.9   
231            6      134             80             37      370  46.2   
..           ...      ...            ...            ...      ...   ...   
71             5      139             64             35      140  28.6   
106            1       96            122              0        0  22.4   
270           10      101             86             37        0  45.6   
435            0      141              0              0        0  42.4   
102            0      125             96              0        0  22.5   

     DiabetesPedigreeFunction  Age  
60                      0.304   21  
618                     1.282   50  


In [9]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()

LR_model.fit(x_train, y_train)

LinearRegression()

In [21]:
x_test = test_set.drop(['Outcome'], axis=1).copy()
y_test = test_set['Outcome']

In [22]:
y_predict = LR_model.predict(x_test)

In [23]:
y_predict

array([ 0.33550028,  0.23809869,  0.1510522 ,  0.2401365 ,  0.48142376,
        0.45257375, -0.17450469,  0.60662287,  0.52417796,  0.70476953,
        0.32360466,  0.85290601,  0.38466612,  0.36056948,  0.09946712,
        0.41539557,  0.17869123,  0.07782301,  0.80730861,  0.51299477,
        0.28090594,  0.08303057,  0.5099157 ,  0.11381771,  0.51325022,
        0.82528549,  0.17892718, -0.0594202 ,  0.28338572,  0.16407949,
        0.83851225,  0.80737515,  0.68154389,  0.7649502 ,  0.56140297,
        0.62123131,  1.06134554,  0.30990775,  0.51752336,  0.63691482,
        0.07075333,  0.57757007,  0.55015462,  0.37541745, -0.07644182,
        0.50119208,  0.59600162,  0.27464761,  0.42477995,  0.9941898 ,
        0.00969584,  0.61763578,  0.73395288,  0.31090975,  0.13456812,
       -0.02536316,  0.71219147, -0.30518218,  0.41994556,  0.67869594,
        0.66891428,  0.3798452 ,  0.2956646 ,  0.288035  ,  0.06813053,
        0.55464338,  0.01368504,  0.6272007 , -0.02033281,  0.63

In [24]:
y_test

668    0
324    0
624    0
690    0
473    0
      ..
355    1
534    0
344    0
296    1
462    0
Name: Outcome, Length: 154, dtype: int64

In [25]:
i = 0
pre = y_predict.copy()
for x in y_predict:
  if x>=0.5:
    pre[i] = 1
    i+=1
  else:
    pre[i] = 0
    i+=1


In [26]:
pre

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0.])

In [27]:
y_predict

array([ 0.33550028,  0.23809869,  0.1510522 ,  0.2401365 ,  0.48142376,
        0.45257375, -0.17450469,  0.60662287,  0.52417796,  0.70476953,
        0.32360466,  0.85290601,  0.38466612,  0.36056948,  0.09946712,
        0.41539557,  0.17869123,  0.07782301,  0.80730861,  0.51299477,
        0.28090594,  0.08303057,  0.5099157 ,  0.11381771,  0.51325022,
        0.82528549,  0.17892718, -0.0594202 ,  0.28338572,  0.16407949,
        0.83851225,  0.80737515,  0.68154389,  0.7649502 ,  0.56140297,
        0.62123131,  1.06134554,  0.30990775,  0.51752336,  0.63691482,
        0.07075333,  0.57757007,  0.55015462,  0.37541745, -0.07644182,
        0.50119208,  0.59600162,  0.27464761,  0.42477995,  0.9941898 ,
        0.00969584,  0.61763578,  0.73395288,  0.31090975,  0.13456812,
       -0.02536316,  0.71219147, -0.30518218,  0.41994556,  0.67869594,
        0.66891428,  0.3798452 ,  0.2956646 ,  0.288035  ,  0.06813053,
        0.55464338,  0.01368504,  0.6272007 , -0.02033281,  0.63

In [28]:
from sklearn.metrics import mean_absolute_error

mea = mean_absolute_error(y_test, pre)
mea

0.24025974025974026

In [30]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, pre)

np.sqrt(mse)

0.4901629731627434

In [31]:
import pickle

filename = 'LR_model.pkl'

with open(filename, 'wb') as file:
  pickle.dump(LR_model, file)